In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
train_df = pd.read_csv("../data/raw/Weather Training Data.csv")
test_df = pd.read_csv("../data/raw/Weather Test Data.csv")

In [3]:
train_df.head()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Row0,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0
1,Row1,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0
2,Row2,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0
3,Row3,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,W,19.0,24.0,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0
4,Row4,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,W,6.0,17.0,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0

In [4]:
test_df.head()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,W,20.0,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,NW,7.0,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,NNW,28.0,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes

In [5]:
print("Training Data Shape:", train_df.shape)
print("Testing Data Shape:", test_df.shape)

Training Data Shape: (99516, 23)
Testing Data Shape: (42677, 22)

In [6]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99516 entries, 0 to 99515
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row ID         99516 non-null  str
 1   Location       99516 non-null  str
 2   MinTemp        99073 non-null  float64
 3   MaxTemp        99286 non-null  float64
 4   Rainfall       98537 non-null  float64
 5   Evaporation    56985 non-null  float64
 6   Sunshine       52199 non-null  float64
 7   WindGustDir    92995 non-null  str
 8   WindGustSpeed  93036 non-null  float64
 9   WindDir9am     92510 non-null  str
 10  WindDir3pm     96868 non-null  str
 11  WindSpeed9am   98581 non-null  float64
 12  WindSpeed3pm   97681 non-null  float64
 13  Humidity9am    98283 non-null  float64
 14  Humidity3pm    97010 non-null  float64
 15  Pressure9am    89768 non-null  float64
 16  Pressure3pm    89780 non-null  float64
 17  Cloud9am       61944 non-null  float64
 18  Cloud3pm       59514 non-null  float64
 19  Temp9am        98902 non-null  float64
 20  Temp3pm        97612 non-null  float64
 21  RainToday      98537 non-null  str
 22  RainTomorrow   99516 non-null  int64
dtypes: float64(16), int64(1), str(6)
memory usage: 19.9 MB

In [7]:
train_df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
count,99073.000000,99286.000000,98537.000000,56985.00000,52199.000000,93036.000000,98581.000000,97681.000000,98283.000000,97010.000000,89768.000000,89780.000000,61944.000000,59514.000000,98902.000000,97612.000000,99516.000000
mean,12.176266,23.218513,2.353024,5.46132,7.615090,39.976966,14.004849,18.650464,68.866376,51.433296,1017.684638,1015.286204,4.447985,4.519122,16.970041,21.681340,0.224677
std,6.390882,7.115072,8.487866,4.16249,3.783008,13.581524,8.902323,8.801827,19.074951,20.777616,7.110166,7.045189,2.886580,2.716618,6.488961,6.931681,0.417372
min,-8.500000,-4.100000,0.000000,0.00000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.500000,978.200000,0.000000,0.000000,-7.000000,-5.100000,0.000000
25%,7.600000,17.900000,0.000000,2.60000,4.800000,31.000000,7.000000,13.000000,57.000000,37.000000,1013.000000,1010.500000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,12.000000,22.600000,0.000000,4.80000,8.400000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.700000,1015.300000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,16.800000,28.200000,0.800000,7.40000,10.600000,48.000000,19.000000,24.000000,83.000000,65.000000,1022.400000,1020.000000,7.000000,7.000000,21.500000,26.400000,0.000000
max,33.900000,48.100000,371.000000,86.20000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,1.000000

In [8]:
train_df.columns

Index(['row ID', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='str')

In [9]:
train_df["RainTomorrow"].value_counts()

RainTomorrow
0    77157
1    22359
Name: count, dtype: int64

In [10]:
missing_values = train_df.isnull().sum().sort_values(ascending=False)

missing_values[missing_values > 0]

Sunshine         47317
Evaporation      42531
Cloud3pm         40002
Cloud9am         37572
Pressure9am       9748
Pressure3pm       9736
WindDir9am        7006
WindGustDir       6521
WindGustSpeed     6480
WindDir3pm        2648
Humidity3pm       2506
Temp3pm           1904
WindSpeed3pm      1835
Humidity9am       1233
Rainfall           979
RainToday          979
WindSpeed9am       935
Temp9am            614
MinTemp            443
MaxTemp            230
dtype: int64

In [11]:
missing_percentage = (train_df.isnull().sum() / len(train_df)) * 100

missing_percentage[missing_percentage > 0].sort_values(ascending=False)

Sunshine         47.547128
Evaporation      42.737851
Cloud3pm         40.196551
Cloud9am         37.754733
Pressure9am       9.795410
Pressure3pm       9.783351
WindDir9am        7.040074
WindGustDir       6.552715
WindGustSpeed     6.511516
WindDir3pm        2.660879
Humidity3pm       2.518188
Temp3pm           1.913260
WindSpeed3pm      1.843925
Humidity9am       1.238997
Rainfall          0.983761
RainToday         0.983761
WindSpeed9am      0.939547
Temp9am           0.616986
MinTemp           0.445155
MaxTemp           0.231119
dtype: float64

In [12]:
print("Number of Locations:", train_df["Location"].nunique())

Number of Locations: 49

In [13]:
categorical_columns = train_df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"{col}: {train_df[col].nunique()} unique values")

row ID: 99516 unique values
Location: 49 unique values
WindGustDir: 16 unique values
WindDir9am: 16 unique values
WindDir3pm: 16 unique values
RainToday: 2 unique values

C:\Users\Farag\AppData\Local\Temp\ipykernel_5776\755534374.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = train_df.select_dtypes(include="object").columns

## Dataset Features Description

| Column | Description |
|---|---|
| Location | City in Australia where weather observation was recorded |
| MinTemp | Minimum temperature during the day (°C) |
| MaxTemp | Maximum temperature during the day (°C) |
| Rainfall | Amount of rainfall recorded (mm) |
| WindGustDir | Direction of strongest wind gust |
| WindGustSpeed | Speed of strongest wind gust (km/h) |
| WindDir9am | Wind direction at 9 AM |
| WindDir3pm | Wind direction at 3 PM |
| WindSpeed9am | Wind speed at 9 AM |
| WindSpeed3pm | Wind speed at 3 PM |
| Humidity9am | Humidity at 9 AM (%) |
| Humidity3pm | Humidity at 3 PM (%) |
| Pressure9am | Atmospheric pressure at 9 AM |
| Pressure3pm | Atmospheric pressure at 3 PM |
| Temp9am | Temperature at 9 AM |
| Temp3pm | Temperature at 3 PM |
| RainToday | Whether it rained today |
| RainTomorrow | Target variable: Whether it will rain tomorrow |